### ISSUE TITLE
Enabling init_fid breaks Fanotify instance

### ISSUE THREAD

**Issue by mheberlein** [baskiton/pyfanotify#2]
Trying to get notifications on all recursive file/directory events relevant for a sync client, I'm setting up this wrapper with
```
fanot = fan.Fanotify(init_fid=True)
fanot.mark(
  '/home',
  ev_types=fan.FAN_CREATE | fan.FAN_MODIFY | fan.FAN_MOVE | fan.FAN_DELETE | fan.FAN_ONDIR,
  [...]
)
```
but am getting this error message:

```bash
fanot = fan.Fanotify(init_fid=True)
  File "/home/[...]/venv/lib/python3.8/site-packages/pyfanotify/__init__.py", line 148, in __init__
    self._fd = ext.init(flags, _INIT_O_FLAGS)
OSError: [Errno 22] Fanotify init error: Invalid argument
```

Some of the event flags require the `FAN_REPORT[_DIR]_FID` flags to be set, this is what enabling `init_fid` in the constructor does.

The MAN page https://man7.org/linux/man-pages/man2/fanotify_init.2.html mentions to also remove the `FAN_CLASS_CONTENT` flag.
If I modify this wrapper and simply delete it, the code starts without errors.
But now it doesn't log any events so this is not a solution. :) Any ideas?

**Comment by baskiton** [comment]
Hello! Thank you for report!
Yes, I made a mistake with the flags during initialization. However, further work with events of the FID type requires other processing methods (see [example 2](https://man7.org/linux/man-pages/man7/fanotify.7.html) "fanotify_fid.c"), which are not currently implemented. I'll try to get this done in the near future.

**Comment by baskiton** [comment]
Check v1.2.0
Please report any problem
