### ISSUE TITLE
Filesystem mark doesn't work on another fs

### ISSUE THREAD

**Issue by sean1245780** [baskiton/pyfanotify#6]
When you're running the fanotify class with a fs mark and you're trying to monitor a folder/file on another filesystem from the one your program is running on, it doesn't do anything.

The solution is to open a readonly fd on the given file or directory (preferebly before marking the fs to be listened to), and to put it in `open_by_handle_at` instead of `AT_FDCWD`.
The problem was that it wasn't able to to open fd as it was from a different fs than the one you wanted monitor, and it returned invalid fd and just ignored it.

**Comment by baskiton** [comment]
Check new version, please
