### ISSUE TITLE
pyfanotify 0.2.1 install failed

### ISSUE THREAD

**Issue by EnderByEndera** [baskiton/pyfanotify#7]
When I tried to install pyfanotify 0.2.1 on my Ubuntu desktop, no matter pip or source code I use, I always got this error below:

   × Building wheel for pyfanotify (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-312
      creating build/lib.linux-x86_64-cpython-312/pyfanotify
      copying pyfanotify/__init__.py -> build/lib.linux-x86_64-cpython-312/pyfanotify
      running build_ext
      building 'pyfanotify.ext' extension
      creating build/temp.linux-x86_64-cpython-312
      creating build/temp.linux-x86_64-cpython-312/src
      gcc -pthread -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/home/endera/PycharmProjects/vince-putido/venv/include -I/usr/local/include/python3.12 -c src/ext.c -o build/temp.linux-x86_64-cpython-312/src/ext.o -std=c99
      src/ext.c: In function ‘pyfanotify_mark’:
      src/ext.c:528:25: error: ‘FAN_MARK_FILESYSTEM’ undeclared (first use in this function); did you mean ‘FAN_MARK_FLUSH’?
                   && flags & (FAN_MARK_FILESYSTEM | FAN_MARK_ONLYDIR)) {
                               ^~~~~~~~~~~~~~~~~~~
                               FAN_MARK_FLUSH
      src/ext.c:528:25: note: each undeclared identifier is reported only once for each function it appears in
      At top level:
      src/ext.c:418:1: warning: ‘fs_list_get_fs’ defined but not used [-Wunused-function]
       fs_list_get_fs(fs_list_t **list, fsid_t *fsid)
       ^~~~~~~~~~~~~~
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyfanotify
Failed to build pyfanotify
ERROR: Could not build wheels for pyfanotify, which is required to install pyproject.toml-based projects

My operating system is Ubuntu 18.04 with core version 5.4.0-150-generic, the Python version is 3.12.0b3.

I really want to try **0.2.1** because when I use 0.2.0, I can't receive events like FAN_CREATE, FAN_DELETE, FAN_MOVE etc. in the FAN_ALL_FID_EVENTS as I tried to run examples/fid.py. These events are really important for me to monitor, so it would be so kind to answer the problem above.

**Comment by baskiton** [comment]
Hello! Thanks for report!
Build error fixed in v0.2.2.

But Ubuntu-18.04 with 5.4 kernel does not support FID events since the base remains 4.15. For FID events you need at least Ubuntu-20.04

**Comment by EnderByEndera** [comment]
Thank you for your kind answer! I appreciate that!

I upgraded my system to Ubuntu 22.04, and v0.2.1 is now working properly.

And also, thank you for releasing v0.2.2. It would be helpful for others.
