### ISSUE TITLE
`FAN_RENAME` not working (?)

### ISSUE THREAD

**Issue by GiorgosXou** [baskiton/pyfanotify#8]
`Kernel: 6.9.1-arch1-1`
`FAN_MOVE` works just fine but `FAN_RENAME` doesn't, so... Any Idea? Am I missing anything?

<details>
<summary>Expand code that I'm using:</summary>

```python
import select

import pyfanotify as fan


def foo(t):
    print('calling `foo` every %s seconds' % t)


if __name__ == '__main__':
    foo_timeout = 1
    fanot = fan.Fanotify(init_fid=True, fn=foo, fn_args=(foo_timeout,), fn_timeout=foo_timeout)
    fanot.mark('/home', is_type='fs', ev_types=fan.FAN_RENAME)
    fanot.start()

    cli = fan.FanotifyClient(fanot, path_pattern='*')
    poll = select.poll()
    poll.register(cli.sock.fileno(), select.POLLIN)
    try:
        while poll.poll():
            x = {}
            for i in cli.get_events():
                i.ev_types = fan.evt_to_str(i.ev_types)
                x.setdefault(i.path, []).append(i)
            if x:
                print(x)
    except:
        print('STOP')

    cli.close()
    fanot.stop()
```

</details>

![issue_pyfanotify_fan_rename_Peek 2024-06-03 08-47](https://github.com/baskiton/pyfanotify/assets/11987271/38de932a-567d-4105-afc4-df1c84328185)

Thankfully `FAN_MOVE` *(from my understanding)* behaves pretty much the exact same way as `FAN_RENAME` but yeah...

![image](https://github.com/baskiton/pyfanotify/assets/11987271/4bba8a20-3696-409b-b659-269701e0bebb)
![image](https://github.com/baskiton/pyfanotify/assets/11987271/8c541a6a-7056-44bf-abbf-2ba8fa063d5f)

**Comment by baskiton** [comment]
Hello. Sorry for the long wait. The module really couldn't work with FAN_RENAME events. Added support for this. Also note that FanotifyData.path now contains a tuple of paths. In the case of FAN_RENAME, the old name comes first, the new name comes second.
Please check if everything is working.

**Comment by GiorgosXou** [comment]
Amazing! seems to work fine for me, thank you!
